[craftmypdf]
api_key1 = "TON_API_KEY_1"
template_id1 = "TON_TEMPLATE_ID_1"
api_key2 = "TON_API_KEY_2"
template_id2 = "TON_TEMPLATE_ID_2"

[smtp]
host = "smtp.tonserveur.com"
port = 587
user = "tonemail@domaine.com"
password = "TON_MOT_DE_PASSE"